version: '3.9'

services:
  node:
    container_name: node_container_12
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    restart: always
    networks:
      - my_app

  postgres:
    container_name: postgres_container_12
    build: ./src/database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: postgres -c logging_collector=on
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - my_app

  pgadmin:
    container_name: pgadmin4_container_12
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - my_app

networks:
  my_app:
    driver: bridge

volumes:
  postgres:
  pgadmin: